In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('trainDataFeatures.tsv', sep='\t', index_col=0)

In [4]:
df.head()

id  sentiment                                             review  \
0  5814_8          1  With all this stuff going down at the moment w...   
1  2381_9          1  \The Classic War of the Worlds\" by Timothy Hi...   
2  7759_3          0  The film starts with a manager (Nicholas Bell)...   
3  3630_4          0  It must be assumed that those who praised this...   
4  9495_8          1  Superbly trashy and wondrously unpretentious 8...   

   Review_Length  amazing  good  aweosme  interesting  terrible  nice  
0           2302        0     0        0            2         0     0  
1            946        0     0        0            0         0     0  
2           2455        0     0        0            0         0     0  
3           2245        0     0        1            0         0     0  
4           2233        0     0        0            0         0     0

In [5]:
columns=df.columns[3:]

In [6]:
columns

Index([u'Review_Length', u'amazing', u'good', u'aweosme', u'interesting',
       u'terrible', u'nice'],
      dtype='object')

In [10]:
x=np.asarray(df[columns])

In [11]:
x

array([[2302,    0,    0, ...,    2,    0,    0],
       [ 946,    0,    0, ...,    0,    0,    0],
       [2455,    0,    0, ...,    0,    0,    0],
       ..., 
       [ 641,    0,    0, ...,    1,    0,    0],
       [1145,    0,    0, ...,    0,    0,    0],
       [ 942,    0,    0, ...,    0,    0,    0]], dtype=int64)

In [12]:
y=np.asarray(df.sentiment.transpose())

In [13]:
y

array([1, 1, 0, ..., 0, 0, 1], dtype=int64)

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [16]:
nb=MultinomialNB()
nb.fit(x,y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [17]:
nb.predict(np.asarray(df[columns]))

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [18]:
np.mean(nb.predict(np.asarray(df[columns]))== df.sentiment)

0.54176000000000002

### Making Kaggle submission wit test data

In [19]:
test_data=pd.read_csv('testData.tsv' , sep='\t')

In [20]:
test_data.head(10)

id                                             review
0  12311_10  Naturally in a film who's main themes are of m...
1    8348_2  This movie is a disaster within a disaster fil...
2    5828_4  All in all, this is a movie for kids. We saw i...
3    7186_2  Afraid of the Dark left me with the impression...
4   12128_7  A very accurate depiction of small time mob li...
5    2913_8  ...as valuable as King Tut's tomb! (OK, maybe ...
6    4396_1  This has to be one of the biggest misfires eve...
7     395_2  This is one of those movies I watched, and won...
8   10616_1  The worst movie i've seen in years (and i've s...
9    9074_9  Five medical students (Kevin Bacon, David Labr...

In [22]:
test_data['Review_Length']=test_data.review.apply(len)

In [23]:
# feature extraction with test data
from sklearn.feature_extraction.text import CountVectorizer
vocab_expand=['aweosme','interesting','good','nice','terrible','amazing']
expand_vectorizer=CountVectorizer(vocabulary=vocab_expand)
expand_bow=expand_vectorizer.fit_transform(test_data.review).todense()
words_expand=list(expand_vectorizer.vocabulary_.keys())
df_expand_bow=pd.DataFrame(expand_bow,index=test_data.index,columns=words_expand)
test_data_expand=test_data.join(df_expand_bow)
test_data_expand.to_csv('testDataFeatures.tsv', sep='\t')

In [24]:
predictions=nb.predict(np.asarray(test_data_expand[columns]))

In [25]:
predictions

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [27]:
submission=pd.DataFrame({'id': test_data.id, 'sentiment' : predictions})

In [32]:
submission.to_csv('submission_kaggle.csv', sep='\t')

In [31]:
ls

data_explore.ipynb        modelling.ipynb        testData.tsv
Feature_extraction.ipynb  submission_kaggle.tsv  trainDataFeatures.tsv
labeledTrainData.tsv      testDataFeatures.tsv
